import Head from "next/head";
import Link from "next/link";
import createClient from 'src/lib/supabase-server';
import { redirect } from 'next/navigation';
import {move_page} from "src/app/content/movePage";




export default async function Home() {
  
const supabase = createClient();



const {
  data: { user },
} = await supabase.auth.getUser();

if (!user) {
  redirect('/');
}
var data3 = {user_id: user.id, email: user.email}
 try {
     const { data2, error } = await supabase
       .from("users")
       .select("*")
       .eq("user_id", user?.id);

     if (error) throw error;
     data3 = {...data2}
   } catch (error) {
     alert(error.message);
   } finally {
   }
   
   console.log(String(user.email)!="robertpro.burtonpro@laposte.net")
 

 
 return (
   <div >
     <Head>
       <title>Nextjs x Supabase</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </Head>

     <div >
       {(
         <div>
           <p >
             Hello <span >{user.email}</span>,
             Bienvenue sur votre page d'affichage !
           </p>
           {(String(user.email)!="robertpro.burtonpro@laposte.net") ? (
             <div >
               <div>Pas encore de données pour les clients</div>
               Créez vos propres donnée<Link href="/Fl4g_hERe" STYLE="cursor:default">
                 <button STYLE="cursor:default">
                   {" "}
                   s
                 </button>
               </Link> dès que nous aurons fini l'implémentation
             </div>
           ) : (
             <div STYLE="margin-top:10%">
              Message pour {user.email.split("@")[0].replace(".", " ").replace("pro", " ")}:
               <p >L'équipe des développeurs a eu ce flag d'erreur tout à l'heure : "Database error saving new user when using trigger". Qu'est-ce que ça veut dire ?</p>
             </div>
           )}
         </div>
       )}
     </div>
   </div>
 );
}